### ISSUE TITLE
Build failure during bitbake elisa-cluster-demo-platform

### ISSUE THREAD

**Issue by sachinmokashi** [elisa-tech/meta-elisa#12]
The latest build is failing while building meta-elisa in Yocto based AGL workspace. 

The following patch will fix the issue:
[http://cgit.openembedded.org/meta-openembedded/commit/?h=master-next&id=74b66d1911118bac53033f77ba6d3923f4809d5a](http://cgit.openembedded.org/meta-openembedded/commit/?h=master-next&id=74b66d1911118bac53033f77ba6d3923f4809d5a)

```
xmlsec1: Fix configure QA error caused by host lookup path
The configure script contains hardcoded lookup paths to /usr and other
paths that might interfere with the host. These are overwritten with the
staging dir locations for Poky compatibility.

Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>
```

**Comment by AGLExport** [comment]
Thank you.
I will discuss to AGL members.

**Comment by dl9pf** [comment]
What is your host distro ?
I'll check the dunfell branch. Thanks for reporting.

**Comment by mokashisachin** [comment]
I am building it on a Ubuntu 18.1 Host. This patch needs to be backported to dunfell and maybe gatesgarth in future, since the configure script in xmlsec1 contains hardcoded lookup paths to /usr and other
paths that might interfere with the host.

**Comment by sudipm-mukherjee** [comment]
I have not tried on Ubuntu but Debian Buster release is ok for me.
I will try it on Ubuntu.

**Comment by cminyard** [comment]
Note that pulling this patch is perfectly fine.  It's from upstream openembedded.  If it fixes the build issue, I don't see an issue.

**Comment by Farshid-Monhaseri** [comment]
The latest image (currently AGL jellyfish) is OK on Ubuntu too

**Comment by pahmann** [comment]
As we are not seeing the issue in the community builds within ELISA and it is more a general yocto thing, proposing this patch to yocto community will be the right path. The clean way will to backport the patch and suggest it to yocto.

**Comment by pahmann** [comment]
One more comment: We are currently migrating from AGL koi to needlefish, which implies an underlying migration from yocto dunfell to kirkstone.
