### ISSUE TITLE
improve meta-elisa readme by specifying kvm option usage.

### ISSUE THREAD

**Issue by pahmann** [elisa-tech/meta-elisa#19]
KVM need to be set in the bios setting  of the host PC or, if you remove KVM option from qemu call it will work, but performance is poor. The setting will differ based on the motherboard, but could be something like  Intel®Virtualization Technology or AMD-V.

**Comment by OpenJohnMacGregor** [comment]
it might be worth mentioning that the option is called "svm support" on my MSI mainboard  and can be found under "Advanced CPU Configuration" in the overclocking section. (see [forum report](https://forum-en.msi.com/index.php?threads/mpg-b550i-gaming-edge-wifi-how-to-enable-amd-v.362152/) [msi docu](https://www.msi.com/faq/nb-1627) - BTW, not always enabled by default), 

I, for one, find that a tad counter-intuitive.

**Comment by pahmann** [comment]
I placed this part to the wiki. It looks a bit like trouble shooting and there are two solutions with by removing the kvm option from the qemu call and accepting a lower performance of the demo or to switch on virtualization support in the hardware setting of the PC. This setting differs depending on Bios and UEFI version used. It depends on the underlying CPU architecture and also on the mainboard manufacturer. A clear answer cannot be provided in the official readme. It makes sense to have this as a general trouble shooting knowledge base. Using the wiki of the repo may serve a a base until there is a better solution for it.

**Comment by pahmann** [comment]
Link to the wiki page: https://github.com/elisa-tech/meta-elisa/wiki/Troubleshooting
