### ISSUE TITLE
-show-cursor option eliminated in qemu 6.0

### ISSUE THREAD

**Issue by OpenJohnMacGregor** [elisa-tech/meta-elisa#23]
Running the demo with the  qemu command documented in the readme now results in the following error message:
qemu-system-x86_64: -show-cursor: invalid option

I'm running qemu 6.1, but a little research revealed that the option was deleted in version 6.0 
([change log](https://wiki.qemu.org/ChangeLog/6.0)).

The log entry says to use  *-display sdl,show-cursor=on* instead, but do we really need to show the cursor?

**Comment by sudipm-mukherjee** [comment]
fwiw, I do not use `-show-cursor` with my scripts to run the image.

**Comment by pahmann** [comment]
@OpenJohnMacGregor I built needlefish based image and saw the parameter in the formal documentation. I will create a PR based on your finding and update the documentation accordingly.

**Comment by pahmann** [comment]
PR created and linked for the issue.

**Comment by pahmann** [comment]
There was an additional comment from @OpenJohnMacGregor in the issue asking about "The log entry says to use -display sdl,show-cursor=on instead, but do we really need to show the cursor?"
We wanted to use the cursor actually to hover over the rendered tell tale to show that the change is detected and an error is displayed. This is not yet a feature of the current demo state.
