### ISSUE TITLE
update docker usage documentation

### ISSUE THREAD

**Issue by pahmann** [elisa-tech/meta-elisa#31]
I sligthly modified the readme:

- I added a section to place the docker file in your desired location where you want to start of with the docker image creation. I could not find this in the readme.
- I had to run the commands for docker build and docker run with sudo rights. This may also require an update.
- Also, I simply installed docker and docker.io from repo without adding the latest version as per docker documentation which is referred to in the readme. Maybe we could say something like use these packages and either follow the docker instructions, if this does not work for your distro or just give it a try with the few packages.
- Next step can be to refer the documentation in the meta-elisa readme readme.md as a good way to start the build. Especially, the script takes away some work for you.
- Change from koi to needlefish once merged

**Comment by sudipm-mukherjee** [comment]
If you follow the steps at
https://docs.docker.com/engine/install/linux-postinstall/ then you will not
need sudo.
I have updated dockerfile for needlefish, will mail you so that you can
test it and place it in the appropriate place,


-- 
Regards
Sudip

**Comment by pahmann** [comment]
Add the sudo handling as additional information to the docker docu to close this item. 
Location of modification is here:  https://github.com/elisa-tech/wg-automotive/tree/master/Docker_container

**Comment by pahmann** [comment]
non-root handling mentioned at: https://github.com/elisa-tech/meta-elisa/issues/31

**Comment by pahmann** [comment]
As per the previous comment the non-root handling is mentioned in the Troubleshooting section [run docker as non-root user](https://github.com/elisa-tech/meta-elisa/wiki/Troubleshooting#i-do-not-want-to-run-docker-as-root-user-what-can-i-do)

This should be added to the documentation for the docker container at the end of the docker installation section https://github.com/elisa-tech/wg-automotive/tree/master/Docker_container#install-docker

It should come after `Install docker from your distro or you can follow instructions at https://docs.docker.com/engine/install/` and be mentioned as: "As a post installation step following the instructions at [Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) enables building and running Docker as non-root user."

**Comment by pahmann** [comment]
@LeandraVoges improved the documentation and the commit is merged into master. This issue is closed.
