### ISSUE TITLE
qemu watchdog argument with qemu v7.2.0

### ISSUE THREAD

**Issue by sudipm-mukherjee** [elisa-tech/meta-elisa#37]
qemu v7.2.0 has removed the use of "-watchdog". Instead of `-watchdog i6300esb` if qemu v7.2.0 is used then the argument needs to be `-device i6300esb`.

**Comment by pahmann** [comment]
I checked that this is backward compatible on my machine. We can update the call in the documentation.

**Comment by pahmann** [comment]
Issue resolved. See linked PR.
