### ISSUE TITLE
OpenQA image comparision of "DANGER sign" is failing

### ISSUE THREAD

**Issue by pahmann** [elisa-tech/meta-elisa#49]
The DANGER warning is no longer visible in the latest execution of the demo in OpenQA testing.

See for example here:
https://openqa.qa.codethink.co.uk/tests/3288#step/safety/8

Compilation in meta-elisa gitlab CI is still successful.

**Comment by sudipm-mukherjee** [comment]
On Tue, 11 Apr 2023 at 15:47, Philipp Ahmann ***@***.***>
wrote:

> The DANGER warning is no longer visible in the latest execution of the
> demo in OpenQA testing.
>
> See for example here:
> https://openqa.qa.codethink.co.uk/tests/3288#step/safety/8
>
> Compilation in meta-elisa gitlab CI is still successful.
>

Just to note, even though CI is successful the screenshot job of the CI
also shows that the DANGER warning is not available.
https://gitlab.com/elisa-tech/meta-elisa-ci/-/jobs/4089619064/artifacts/file/screenshot/screenshot_20230411_001330.jpeg

-- 
Regards
Sudip

**Comment by pahmann** [comment]
Just talked to AGL in their regular meeting. There has not been an update on needlefish qemu recently. The last one was on sound parameter in qemu. Even that was few days earlier than this change. The identified change on the compositor as put in the automotive WG meeting notes point to master and not to needlefish branch. Also this should not be an issue. 
Further analysis might be needed. Maybe we can have a look on Monday
@sudipm-mukherjee FYI.

**Comment by pahmann** [comment]
Just an update, @sudipm-mukherjee was looking at this problem. And looks like it has
been caused by expired certificates. These certificates are used by the
kuksa components which manage the CAN signals.
Those certificates expired on "Apr  7 14:35:34 2023 GMT" and our tests
started failing from that night onward.

Sudip has raised https://jira.automotivelinux.org/browse/SPEC-4767 for AGL
people.

He also reported the status on the man list.

**Comment by pahmann** [comment]
Test is working again: https://openqa.qa.codethink.co.uk/tests/3451#step/safety/1
Jira issue at AGL is marked as resolved: https://jira.automotivelinux.org/browse/SPEC-4767

This item can be closed.
